INSERT INTO Cake (ID, NAME, DESCRIPTION) VALUES (1, 'BlackForest', 'black');
INSERT INTO Cake (ID, NAME, DESCRIPTION) VALUES (2, 'WhiteForest', 'white');
INSERT INTO Cake (ID, NAME, DESCRIPTION) VALUES (3, 'RedVelver', 'red');

INSERT into CAKEUSER(ID,USERNAME,PASSWORD) VALUES(1, 'Rose', '$2a$12$74lFHxtWvW8m/ajeAbl8WO8K6InW9Gh3fmjPBEpJVHLEPgSZhNaXi');